Lab1
OlichkaKr/mobile-development pull request #1
Opened 2019-09-23 00:24 UTC by OlichkaKr

2019-09-23 00:32 UTC, OlichkaKr commented
@ovovchak

2019-09-27 13:02 UTC, nvipash requested changes
First review of Laboratory work #1
General comments:

- ignore .idea folder
- variables naming
- delete tests
- code formatting
- back stack logic doesn't exist (6th point of the task)

2019-09-27 13:02 UTC, nvipash commented on XenOne/.gitignore
> +/.idea/assetWizardSettings.xml
варто було лише вказати `.idea/`, так як попереду / - цю папку все одно додало

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/.gitignore
> +/build
цей .gitignore зайвий

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
тобі не потрібні тести в dependecies

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/androidTest/java/com/iot/xenone/ExampleInstrumentedTest.java
> +package com.iot.xenone;
частину з тестами треба прибрати, так як вам вони не потрібні

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/AndroidManifest.xml
> +        <activity android:name=".WelcomeActivity"></activity>
це мав би бути self-closed елемент

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignInActivity.java
> +                            Toast.makeText(SignInActivity.this, "Incorrect email or password",
текст мав би бути в strings.xml та витягуватись з нього

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignUpActivity.java
> +            }
для чого ці пусті реалізації методів?

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignUpActivity.java
> +    private void signUp(final String email, final String username, final String password, final String phone){
мала б бути пуста стрічка між методами

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignUpActivity.java
> +    private DatabaseReference mDatabase;
з назвами варто дотримуватись, як і загалом в code styling, консистентності. не варто одну private змінну починати з `m`,а іншу ні

https://source.android.com/setup/contribute/code-style#follow-field-naming-conventions

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignUpActivity.java
> +    private TextInputLayout passwordEditText;
в назві вказано `EditText`, але об'єкт класу TextInputLayout

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignInActivity.java
> +
зайва пуста стрічка

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignInActivity.java
> +        }
60-86 стрічки різне форматування if'ів, немає консистентності

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignInActivity.java
> +            signIn(emailEditText.getEditText().getText().toString(), passwordEditText.getEditText().getText().toString());
перевір чи незадовга стрічка

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignInActivity.java
> +        // [START sign_in_with_email]
дивне оформлення коментара

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignUpActivity.java
> +
зайва пуста стрічка

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignUpActivity.java
> +
зайва пуста стрічка

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignUpActivity.java
> +        else if (!emailInput.matches("[a-zA-Z0-9._-]+@[a-z]+\\.+[a-z]+")){
я би такі регулярки виносив у константи

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignUpActivity.java
> +                        phoneEditText.getEditText().getText().toString());
ось так не варто передавати у методи значення. по-перше, дуже важко читається, а по-друге дууже роздувається виклик методу

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/SignUpActivity.java
> +        else{
переглянь, тут теж if-и некоректно відформатовані

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/WelcomeActivity.java
> +                }
те саме, для чого ці пусті реалізації методів?

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/WelcomeActivity.java
> +    private DatabaseReference mDatabase;
в SignUpActivity.java звертав увагу на це

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/WelcomeActivity.java
> +        signOut();
а нащо тобі 2 окремі методи signOut?

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/java/com/iot/xenone/extraclasses/User.java
> +
зайві 2 пусті стрічки

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/main/res/values/strings.xml
> +    <string name="sign_out">Sign Out</string>
тут не весь текст

2019-09-27 13:02 UTC, nvipash commented on XenOne/app/src/test/java/com/iot/xenone/ExampleUnitTest.java
> +package com.iot.xenone;
ці тести варто видалити, вони зайві

2019-09-30 20:42 UTC, OlichkaKr commented on XenOne/app/src/main/java/com/iot/xenone/SignUpActivity.java
> +            }
Я використовую інтерфейс ChildEventListener, відповідно повинна реалізувати всі його методи

2019-11-30 23:32 UTC, merged